### ISSUE TITLE
configs.json data?

### ISSUE THREAD

**Issue by asmaloney** [NothNoth/cfmagic#2]
Where does `configs.json` come from?

Is it generated somewhere or did you make it by hand?

**Comment by NothNoth** [comment]
Hi,

As said in the README:  "The configs.json file has been taken from https://github.com/zed0/clang-format-configurator, all credits to him."

Note sure it has been updated for newer versions..

**Comment by asmaloney** [comment]
Oh sorry - I missed that. I was looking through the code :-)
